### ISSUE TITLE
paredit:deleteFwd skips a character

### ISSUE THREAD

**Issue by victor-acuna** [mme/atom-paredit#1]
Hitting the `DEL` key or pressing `C-d` does delete the character following the cursor, but then proceeds to skip one character after deleting. 

So, for example, if the cursor is `|` and I start with something like `(foo |bar)` then hit `DEL`, I end up with `(foo a|r)`.

I'm not familiar with how paredit works in emacs; is this the expected functionality, or am I correct in thinking this is an issue? I suppose I may also have another package that is colliding with paredit, although the only community packages I have installed are this one, minimap, and minimap-git-diff.

Anyway, I have overridden the `DEL` key in my keymap with `core:delete` for now. This means I lose paren balancing on deletion, though. Otherwise this package has been great!

**Comment by mme** [comment]
Thanks for the bug report. Glad you find the package useful!
